"""add user status

Revision ID: 20eeb96ac805
Revises: 5ec3cf1559ad
Create Date: 2026-06-14 13:23:30.806321
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20eeb96ac805'
down_revision: Union[str, None] = '5ec3cf1559ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'status',
            sa.String(length=20),
            nullable=False,
            server_default='active'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
