"""add priority and reminder to todos

Revision ID: 6ea92154e6f7
Revises: a481c6386c48
Create Date: 2026-06-16 23:49:20.814184
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ea92154e6f7'
down_revision: Union[str, None] = 'a481c6386c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('todos', sa.Column('reminder_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'reminder_time')
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
